variables:
  CTEST_OUTPUT_ON_FAILURE: '1'

stages:
  - test
  - coverage
  - package

#
# Test
#
Test Ubuntu 22.04:
  stage: test
  image: ubuntu:22.04
  script:
    - DEBIAN_FRONTEND=noninteractive apt update -y
    - DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends cmake build-essential git libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-base python3-dev
    - rm -rf build && mkdir build && cd build
    - cmake ..
    - make -j${nproc}
    - make test
  except:
    - develop
    - master

#
# Coverage
#
coverage:
  stage: coverage
  image: ubuntu:22.04
  script: 
    - DEBIAN_FRONTEND=noninteractive apt update -y
    - DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends lcov zip
    - DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends cmake build-essential git libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-base python3-dev
    - rm -rf build && mkdir build && cd build
    - cmake -DTEST_COVERAGE=ON ..
    - make -j$(nproc)
    - make check_coverage
    - zip -r coverage.zip coverage
    - mv coverage.zip ../
  artifacts:
    name: "shmdata_coverage_${CI_BUILD_REF_NAME}"
    paths:
    - "coverage.zip"
  only:
    - develop

#
# Package
#
Debian Package Ubuntu 22.04:
  stage: package
  image: ubuntu:22.04
  script: 
    - DEBIAN_FRONTEND=noninteractive apt update -y
    - DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends file
    - DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends cmake build-essential git libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-base python3-dev
    - rm -rf build && mkdir build && cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr ..
    - make package
    - mv *.deb ../libshmdata_latest_amd64.deb
  artifacts:
    name: "shmdata_package_${CI_BUILD_REF_NAME}"
    paths:
    - libshmdata_latest_amd64.deb
  only:
    - master
