image: docker:18

services:
  - docker:dind

variables:
  BUILD_DIR: /opt/shmdata
  DOCKERFILE_PATH: dockerfiles/Dockerfile

stages:
  - configure
  - test
  - test-package
  - deploy

Build and Deploy CI image:
  stage: configure
  variables:
    CONTAINER_TAG: $CI_REGISTRY/sat-metalab/shmdata:ci
    BUILD_TYPE: Debug
  script:
    - docker build -t $CONTAINER_TAG --build-arg BUILD_TYPE=$BUILD_TYPE -f $DOCKERFILE_PATH --target build .
    - echo $CI_DEPLOY_PASSWORD | docker login -u $CI_DEPLOY_USER --password-stdin $CI_REGISTRY
    - docker push $CONTAINER_TAG

Test:
  stage: test
  image: $CI_REGISTRY/sat-metalab/shmdata:ci
  script:
    - cd $BUILD_DIR/build
    - make test

Test package:
  stage: test-package
  image: $CI_REGISTRY/sat-metalab/shmdata:ci
  script:
    - cd $BUILD_DIR/build
    - make package_source_test

Build and Deploy clean image:
  stage: deploy
  variables:
    CONTAINER_TAG: $CI_REGISTRY/sat-metalab/shmdata:$CI_COMMIT_REF_NAME
  script:
    - docker build -t $CONTAINER_TAG -f $DOCKERFILE_PATH .
    - echo $CI_DEPLOY_PASSWORD | docker login -u $CI_DEPLOY_USER --password-stdin $CI_REGISTRY
    - docker push $CONTAINER_TAG
  only:
    - develop
    - master
