stages:
  - test-ubuntu18.04
  - test-package
  - coverage

Test:
  stage: test-ubuntu18.04
  image: ubuntu:18.04
  script:
    - DEBIAN_FRONTEND=noninteractive apt update -y
    - DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends cmake build-essential git libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-base python3-dev
    - rm -rf build && mkdir build && cd build
    - cmake ..
    - make -j${nproc}
    - make test
  except:
    - develop
    - master

Test package:
  stage: test-package
  image: ubuntu:20.04
  script:
    - DEBIAN_FRONTEND=noninteractive apt update -y
    - DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends cmake build-essential git libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-base python3-dev
    - rm -rf build && mkdir build && cd build
    - cmake ..
    - make package_source_test
  only:
    - develop
    - master

#
# Test coverage
#
coverage:
  stage: coverage
  image: ubuntu:20.04
  script: 
    - DEBIAN_FRONTEND=noninteractive apt update -y
    - DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends lcov zip
    - DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends cmake build-essential git libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-base python3-dev
    - rm -rf build && mkdir build && cd build
    - cmake -DTEST_COVERAGE=ON ..
    - make -j$(nproc)
    - make check_coverage
    - zip -r coverage.zip coverage
    - mv coverage.zip ../
  artifacts:
    name: "shmdata_coverage_${CI_BUILD_REF_NAME}"
    paths:
    - "coverage.zip"
  only:
    - develop
